### ISSUE TITLE
Help regarding multiome samples integration

### ISSUE THREAD

**Issue by annepureddy** [punnaug/MultiomeSingleCell#1]
Hi @punnaug 

I am trying to integrate multiple samples with 10X multiome Data: scRNA and scATAC from the same cell. Your MultiomeSingleCell code piece has been extremely helpful. However, I have a quick question about **why and how** you are removing non-common cells in the multiome data. Does this mean that the seurat object containing RNA data needs to have the same cells as counts data from ATAC? When I am trying to create the Chromatin Assay I am getting the following error: 

`FC013_1[["ATAC"]] <- CreateChromatinAssay(counts = FC013_1.counts, sep = c(":", "-"), fragments = frags.FC013_1, annotation = annotation)`
_Error: cannot add a different number of cells than already present_

It would be great if you could please help me with this issue! Thank you!

**Comment by punnaug** [comment]
Hi, Sorry for the delayed response.
It seems like you have inconsistent number of cells when trying to combine the assay into one object. I'm referring you to this thread, hope it helps.
https://github.com/stuart-lab/signac/issues/570
[https://opengraph.githubassets.com/6842d3fc74f7afeea7a2fe16c608a3a3d15460583987076b922bede3ecbce8ea/stuart-lab/signac/issues/570]<https://github.com/stuart-lab/signac/issues/570>
Cell Barcodes not matching in input: Cannot add a different number of cells than already present · Issue #570 · stuart-lab/signac<https://github.com/stuart-lab/signac/issues/570>
Hi, I am using Signac for getting back more cells by customized filtering threshold, so, I have to use the "raw_feature_bc_matrix" instead of the "filtered_feature_bc_matrix". Don't know whether it...
github.com

________________________________
From: annepureddy ***@***.***>
Sent: Thursday, September 21, 2023 8:57 AM
To: punnaug/MultiomeSingleCell ***@***.***>
Cc: Punn Augsornworawat ***@***.***>; Mention ***@***.***>
Subject: [punnaug/MultiomeSingleCell] Help regarding multiome samples integration (Issue #1)


Hi @punnaug<https://github.com/punnaug>

I am trying to integrate multiple samples with 10X multiome Data: scRNA and scATAC from the same cell. Your MultiomeSingleCell code piece has been extremely helpful. However, I have a quick question about why and how you are removing non-common cells in the multiome data. Does this mean that the seurat object containing RNA data needs to have the same cells as counts data from ATAC? When I am trying to create the Chromatin Assay I am getting the following error:

FC013_1[["ATAC"]] <- CreateChromatinAssay(counts = FC013_1.counts, sep = c(":", "-"), fragments = frags.FC013_1, annotation = annotation)
Error: cannot add a different number of cells than already present

It would be great if you could please help me with this issue! Thank you!
